import { test } from '@e2e-dev/web'
import { expect } from 'e2e'
import { memberSession, mutationPermission, testName } from './support'

test.describe('Durable conversations', { ...memberSession(), ...mutationPermission, tags: ['web', 'chat', 'mutations'], timeout: 180_000 }, () => {
  test('human DM sends, survives reload, searches history and opens its canvas', async ({ app, screen, browser }) => {
    const peer = process.env.E2E_PEER_NAME
    test.skip(!peer, 'Set E2E_PEER_NAME to another human in the seeded project; requires live WuKongIM.')
    const message = testName('durable message')
    await app.open('/')
    await screen.getByRole('button', '新建对话').tap()
    const dialog = screen.getByRole('dialog', '新建对话')
    await dialog.getByLabel('搜索参与者').fill(peer!)
    await dialog.getByRole('checkbox').first().check()
    await dialog.getByRole('button', '开始对话').tap()
    await expect(dialog).toBeHidden()
    await browser.locator('[contenteditable="true"]').fill(message)
    await screen.getByRole('button', '发送').tap()
    await expect(screen.getByText(message, { exact: true })).toBeVisible()
    await browser.reload()
    await screen.getByLabel('搜索会话和消息').fill(peer!)
    await browser.locator('[data-slot="sidebar"] [role="button"]').filter({ has: screen.getByText(peer!, { exact: true }) }).tap()
    await expect(screen.getByText(message, { exact: true })).toBeVisible()
    await browser.keyboard.press('ControlOrMeta+f')
    await screen.getByPlaceholder('搜索当前会话…').fill(message)
    await expect(screen.getByRole('button', '下一个匹配')).toBeEnabled()
    await screen.getByRole('button', '关闭搜索').tap()
    const original = browser.locator('[data-msg-id]').filter({ hasText: message })
    await original.hover()
    await original.getByRole('button', '回复').tap()
    await expect(screen.getByRole('button', '取消回复')).toBeVisible()
    const reply = testName('quoted reply')
    await browser.locator('[contenteditable="true"]').fill(reply)
    await screen.getByRole('button', '发送').tap()
    await expect(screen.getByText(reply, { exact: true })).toBeVisible()
    await expect(browser.locator('[data-msg-id]').filter({ hasText: reply }).getByRole('button', message)).toBeVisible()
    await browser.reload()
    await expect(browser.locator('[data-msg-id]').filter({ hasText: reply }).getByRole('button', message)).toBeVisible()
    await screen.getByRole('button', '打开画布预览').tap()
    await screen.getByRole('button', /^打开完整画布：/).tap()
    await expect(screen.getByRole('dialog', 'Canvas')).toBeVisible()
    await screen.getByRole('button', '返回对话').tap()
    await expect(screen.getByRole('dialog', 'Canvas')).toBeHidden()
    await expect(screen.getByRole('button', '打开画布预览')).toBeFocused()

    const row = browser.locator('[data-slot="sidebar"] [role="button"]').filter({ has: screen.getByText(peer!, { exact: true }) })
    await row.secondaryTap()
    // Restore both preferences after checking their persisted state.
    const wasPinned = await screen.getByRole('menuitem', '取消置顶').count() === 1
    await screen.getByRole('menuitem', wasPinned ? '取消置顶' : '置顶会话').tap()
    await expect(screen.getByText(wasPinned ? '已取消置顶' : '会话已置顶', { exact: true })).toBeVisible()
    await row.secondaryTap()
    const wasMuted = await screen.getByRole('menuitem', '取消静音').count() === 1
    await screen.getByRole('menuitem', wasMuted ? '取消静音' : '静音会话').tap()
    await expect(screen.getByText(wasMuted ? '已取消静音' : '会话已静音', { exact: true })).toBeVisible()
    await browser.reload()
    await row.secondaryTap()
    await expect(screen.getByRole('menuitem', wasPinned ? '置顶会话' : '取消置顶')).toBeVisible()
    await screen.getByRole('menuitem', wasMuted ? '静音会话' : '取消静音').tap()
    await expect(screen.getByText(wasMuted ? '会话已静音' : '已取消静音', { exact: true })).toBeVisible()
    await row.secondaryTap()
    await screen.getByRole('menuitem', wasPinned ? '置顶会话' : '取消置顶').tap()
    await expect(screen.getByText(wasPinned ? '会话已置顶' : '已取消置顶', { exact: true })).toBeVisible()
  })

  test('a named group persists and mobile navigation returns to the conversation list', async ({ app, screen, browser }) => {
    const peers = (process.env.E2E_GROUP_PEERS ?? '').split('|').filter(Boolean)
    test.skip(peers.length < 2, 'Set E2E_GROUP_PEERS to two seeded human names separated by |; requires live WuKongIM.')
    const title = testName('group')
    await browser.setViewport({ width: 390, height: 844 })
    await app.open('/')
    await screen.getByRole('button', '新建对话').tap()
    const dialog = screen.getByRole('dialog', '新建对话')
    for (const peer of peers.slice(0, 2)) {
      await dialog.getByLabel('搜索参与者').fill(peer)
      await dialog.getByRole('checkbox').first().check()
    }
    await dialog.getByLabel('群聊名称（可选）').fill(title)
    await dialog.getByRole('button', '创建群聊').tap()
    await expect(screen.getByRole('button', '返回会话列表')).toBeVisible()
    await expect(screen.getByText(title, { exact: true })).toBeVisible()
    await screen.getByRole('button', '返回会话列表').tap()
    await expect(screen.getByLabel('搜索会话和消息')).toBeVisible()
    await browser.reload()
    await screen.getByLabel('搜索会话和消息').fill(title)
    await browser.locator('[data-slot="sidebar"] [role="button"]').filter({ hasText: title }).tap()
    await expect(screen.getByRole('button', '返回会话列表')).toBeVisible()
    await screen.getByRole('button', '返回会话列表').tap()
    await browser.locator('[data-slot="sidebar"] [role="button"]').filter({ hasText: title }).secondaryTap()
    await screen.getByRole('menuitem', '退出群聊').tap()
    await screen.getByRole('alertdialog').getByRole('button', '退出群聊').tap()
    await expect(screen.getByText('已退出群聊', { exact: true })).toBeVisible()
    await browser.reload()
    await screen.getByLabel('搜索会话和消息').fill(title)
    await expect(screen.getByText('没有找到匹配结果', { exact: true })).toBeVisible()
  })
})
