import { test } from '@e2e-dev/web'
import { expect } from 'e2e'
import { memberSession, mutationPermission } from './support'

test.describe('Saved account preferences', { ...memberSession(), ...mutationPermission, tags: ['web', 'settings', 'mutations'] }, () => {
  test('notification times and switches persist after reload', async ({ app, screen, browser }) => {
    await app.open('/')
    await screen.getByRole('button', '打开账户菜单').tap()
    await screen.getByRole('menuitem', '设置').tap()
    await screen.getByRole('button', '通知').tap()
    await screen.getByLabel('通知时区').fill('Asia/Shanghai')
    await screen.getByLabel('每日和每周摘要发送时间').fill('10:35')
    await screen.getByRole('combobox', '每周摘要发送日').tap()
    await screen.getByRole('option', '周五').tap()
    await screen.getByLabel('安静时段开始时间').fill('21:30')
    await screen.getByLabel('安静时段结束时间').fill('07:15')
    await screen.getByRole('switch', '邮件通知').uncheck()
    await screen.getByRole('switch', '应用内通知').check()
    await screen.getByRole('button', '保存通知设置').tap()
    await expect(screen.getByText(/^已保存“.+”的通知设置$/)).toBeVisible()
    await browser.reload()
    await screen.getByRole('button', '打开账户菜单').tap()
    await screen.getByRole('menuitem', '设置').tap()
    await screen.getByRole('button', '通知').tap()
    await expect(screen.getByLabel('通知时区')).toHaveValue('Asia/Shanghai')
    await expect(screen.getByLabel('每日和每周摘要发送时间')).toHaveValue('10:35')
    await expect(screen.getByRole('combobox', '每周摘要发送日')).toContainText('周五')
    await expect(screen.getByLabel('安静时段开始时间')).toHaveValue('21:30')
    await expect(screen.getByLabel('安静时段结束时间')).toHaveValue('07:15')
    await expect(screen.getByRole('switch', '邮件通知')).not.toBeChecked()
    await expect(screen.getByRole('switch', '应用内通知')).toBeChecked()
  })

  test('generated and uploaded avatars save and survive reload', async ({ app, screen, browser }) => {
    await app.open('/')
    await screen.getByRole('button', '打开账户菜单').tap()
    await screen.getByRole('menuitem', '设置').tap()
    await screen.getByRole('button', '修改个人头像').tap()
    const dialog = screen.getByRole('dialog', '修改个人头像')
    await dialog.getByRole('button', '随机换一个').tap()
    const generated = await dialog.getByRole('img', '头像预览').getAttribute('src')
    await dialog.getByRole('button', '保存头像').tap()
    await expect(dialog).toBeHidden()
    await expect(browser.locator('[aria-label="修改个人头像"] img')).toHaveAttribute('src', generated!)
    await browser.reload()
    await screen.getByRole('button', '打开账户菜单').tap()
    await screen.getByRole('menuitem', '设置').tap()
    await expect(browser.locator('[aria-label="修改个人头像"] img')).toHaveAttribute('src', generated!)
    await screen.getByRole('button', '修改个人头像').tap()
    await dialog.getByLabel('上传图片').setInputFiles(['public/icon-192.png'])
    await dialog.getByRole('button', '保存头像').tap()
    await expect(dialog).toBeHidden()
    const uploaded = await browser.locator('[aria-label="修改个人头像"] img').getAttribute('src')
    expect(uploaded).not.toBe(generated)
    await browser.reload()
    await screen.getByRole('button', '打开账户菜单').tap()
    await screen.getByRole('menuitem', '设置').tap()
    await expect(browser.locator('[aria-label="修改个人头像"] img')).toHaveAttribute('src', uploaded!)
    expect(await browser.evaluate(() => {
      const image = document.querySelector<HTMLImageElement>('[aria-label="修改个人头像"] img')
      return Boolean(image?.complete && image.naturalWidth > 0)
    })).toBe(true)
  })
})
