import { expect, test } from '@playwright/test'

const fixture = '/e2e/responsive-shell.html?theme=light'
test.setTimeout(60_000)

test('767px uses the workspace rail with list/chat pages and mobile drawers', async ({ page }) => {
  await page.setViewportSize({ width: 767, height: 900 })
  await page.goto(fixture, { waitUntil: 'domcontentloaded' })

  const shell = page.locator('[data-mobile="true"]')
  await expect(shell).toBeVisible()
  await expect(page.locator('[data-workspace-titlebar]')).toHaveCount(0)
  await expect(page.getByRole('complementary')).toBeVisible()
  const mobileTitle = page.locator('[data-mobile-workspace-title]')
  await expect(mobileTitle).toHaveText('我的学习')
  const titleBox = await mobileTitle.boundingBox()
  const searchBox = await page.getByRole('textbox', { name: '搜索会话和消息' }).boundingBox()
  expect(titleBox && searchBox && titleBox.y < searchBox.y).toBe(true)
  expect((await page.getByRole('navigation', { name: '工作区' }).boundingBox())?.width).toBe(64)

  await page.getByRole('button', { name: '打开账户菜单' }).click()
  const accountDrawer = page.locator('[data-slot="drawer-content"][data-vaul-drawer-direction="bottom"]')
  await expect(accountDrawer).toBeVisible()
  await expect(accountDrawer.getByRole('tablist', { name: '设置栏目' })).toBeVisible()
  await expect(accountDrawer.getByRole('tab')).toHaveCount(4)
  await expect(accountDrawer.locator('[data-slot="tabs-trigger"] > :not(.sr-only)')).toHaveCount(4)
  await accountDrawer.getByRole('tab', { name: '退出登录与账号' }).click()
  await expect(accountDrawer.getByRole('button', { name: '退出登录', exact: true })).toBeVisible()
  await accountDrawer.getByRole('button', { name: '关闭设置' }).click()

  await page.getByText('产品研究协作', { exact: true }).click()
  await expect(page.getByRole('button', { name: '返回会话列表' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: '工作区' })).toHaveCount(0)
  await expect(page.getByText('第一轮完成：三个高频障碍都有访谈出处')).toBeVisible()
  await expect(page.getByRole('toolbar', { name: '消息操作' })).toHaveCount(0)
  await expect.poll(async () => (await page.locator('.chat-message-avatar').first().boundingBox())?.width).toBeLessThanOrEqual(32.5)

  const messageBubble = page.locator('[data-message-bubble="assistant"]').first()
  await messageBubble.dispatchEvent('pointerdown', { pointerId: 1, pointerType: 'touch', isPrimary: true, button: 0, clientX: 120, clientY: 320 })
  await page.waitForTimeout(500)
  const reactionList = page.getByRole('listbox', { name: '快速回应' })
  await expect(reactionList).toBeVisible()
  await expect(reactionList.getByRole('option')).toHaveCount(6)
  await expect(page.getByRole('button', { name: '回复', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '复制', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '回复', exact: true }).click()
  await expect(page.getByRole('button', { name: '取消回复' })).toBeVisible()

  const contextTrigger = page.getByRole('button', { name: '展开资料与 Canvas 工作区' })
  await contextTrigger.click()
  await expect(page.locator('[data-context-layout="flat-stacked"]')).toBeVisible()
  await page.getByRole('button', { name: '打开 用户访谈摘要' }).click()
  await expect(page.getByRole('heading', { name: '用户访谈摘要' })).toBeVisible()
  await page.getByRole('button', { name: '关闭资料' }).click()
  await expect(contextTrigger).toBeFocused()
  await expect(page.locator('[data-context-layout="flat-stacked"]')).toBeHidden()

  await contextTrigger.click()
  await page.getByRole('button', { name: '打开完整画布' }).click()
  await expect(page.locator('[data-canvas-ui="root"]')).toBeVisible()
  await expect(page.locator('[data-slot="dialog-content"]')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-canvas-ui="root"]')).toBeHidden()
  await expect(contextTrigger).toBeFocused()
  await expect(page.locator('[data-context-layout="flat-stacked"]')).toBeHidden()

  await contextTrigger.click()
  await page.evaluate(() => window.responsiveShellFixture.openCalendar())
  await expect(page.getByRole('heading', { name: '移动端方案评审' })).toBeVisible()
  await page.getByRole('button', { name: '关闭' }).click()
  await expect(page.locator('[data-context-layout="flat-stacked"]')).toBeHidden()

  await page.getByRole('button', { name: '返回会话列表' }).click()
  await expect(page.getByRole('navigation', { name: '工作区' })).toBeVisible()
  await page.getByRole('button', { name: '切换到产品设计营' }).click()
  await expect(page.getByRole('complementary')).toBeVisible()
  await expect(page.getByText('产品研究协作', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '切换到我的学习' }).click()

  await page.getByRole('button', { name: '打开学习看板' }).click()
  await expect(page.locator('[data-mobile-dashboard]')).toBeVisible()
  await expect(page.getByRole('combobox', { name: '切换个人学习区或课程' })).toBeVisible()
  await expect(page.getByRole('tablist', { name: '切换看板栏目' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '学习概览' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('768px restores the desktop conversation layout', async ({ page }) => {
  await page.setViewportSize({ width: 768, height: 900 })
  await page.goto(fixture, { waitUntil: 'domcontentloaded' })

  await expect(page.locator('[data-mobile="false"]')).toBeVisible()
  await expect(page.locator('[data-workspace-titlebar]')).toBeVisible()
  await expect(page.locator('#desktop-three-panel-layout')).toBeVisible()
  await expect(page.getByRole('button', { name: '返回会话列表' })).toHaveCount(0)
  await expect(page.getByLabel('调整会话列表宽度')).toBeVisible()
  await expect(page.getByLabel('调整资料与 Canvas 工作区宽度')).toBeVisible()
})

test('1440x900 keeps desktop chat context and the two-column dashboard', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(fixture, { waitUntil: 'domcontentloaded' })

  await expect(page.locator('#desktop-three-panel-layout')).toBeVisible()
  await expect(page.locator('[data-context-layout="flat-stacked"]')).toBeVisible()
  await expect(page.getByText('用户访谈摘要', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '打开完整画布' }).click()
  await expect(page.locator('[data-slot="dialog-content"] [data-canvas-ui="root"]')).toBeVisible()
  await page.keyboard.press('Escape')

  await page.getByRole('button', { name: '打开学习看板' }).click()
  await expect(page.locator('#dashboard-two-panel-layout')).toBeVisible()
  await expect(page.locator('[data-mobile-dashboard]')).toHaveCount(0)
  await expect(page.getByLabel('调整看板侧边栏宽度')).toBeVisible()
})
